-- MySQL Script generated by MySQL Workbench
-- Tue Nov  5 12:27:05 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema f1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema f1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `f1` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `f1` ;

-- -----------------------------------------------------
-- Table `f1`.`circuits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `f1`.`circuits` (
  `circuitId` INT(100) NOT NULL,
  `circuitRef` VARCHAR(14) NULL DEFAULT NULL,
  `name` VARCHAR(38) NULL DEFAULT NULL,
  `location` VARCHAR(21) NULL DEFAULT NULL,
  `country` VARCHAR(12) NULL DEFAULT NULL,
  `lat` DECIMAL(10,0) NULL DEFAULT NULL,
  `lng` DECIMAL(10,0) NULL DEFAULT NULL,
  `alt` INT(11) NULL DEFAULT NULL,
  `url` VARCHAR(71) NULL DEFAULT NULL,
  `driver_FIELD1` INT(11) NOT NULL,
  PRIMARY KEY (`circuitId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `f1`.`statue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `f1`.`statue` (
  `statusId` INT(11) NOT NULL,
  `statu` VARCHAR(18) NOT NULL,
  `circuits_circuitId` INT(100) NOT NULL,
  `circuits_circuitId1` INT(100) NOT NULL,
  PRIMARY KEY (`statusId`, `circuits_circuitId1`),
  INDEX `fk_statue_circuits1_idx` (`circuits_circuitId1` ASC) VISIBLE,
  CONSTRAINT `fk_statue_circuits1`
    FOREIGN KEY (`circuits_circuitId1`)
    REFERENCES `f1`.`circuits` (`circuitId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `f1`.`driver`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `f1`.`driver` (
  `FIELD1` INT(11) NOT NULL,
  `driverId` INT(11) NOT NULL,
  `driverRef` VARCHAR(18) NOT NULL,
  `number` DECIMAL(4,1) NOT NULL,
  `code` VARCHAR(3) NOT NULL,
  `forename` VARCHAR(17) NOT NULL,
  `surname` VARCHAR(23) NOT NULL,
  `dob` VARCHAR(10) NOT NULL,
  `nationality` VARCHAR(17) NOT NULL,
  `driver_FIELD1` INT(11) NOT NULL,
  `statue_statusId` INT(11) NOT NULL,
  PRIMARY KEY (`FIELD1`, `statue_statusId`),
  INDEX `fk_driver_statue1_idx` (`statue_statusId` ASC) VISIBLE,
  CONSTRAINT `fk_driver_statue1`
    FOREIGN KEY (`statue_statusId`)
    REFERENCES `f1`.`statue` (`statusId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `f1`.`controls`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `f1`.`controls` (
  `FIELD1` INT(11) NOT NULL,
  `constructorResultsId` INT(11) NOT NULL,
  `raceId` INT(11) NOT NULL,
  `constructorId` INT(11) NOT NULL,
  `points` DECIMAL(4,1) NOT NULL,
  `driver_FIELD1` INT(11) NOT NULL,
  PRIMARY KEY (`FIELD1`),
  INDEX `fk_controls_driver1_idx` (`driver_FIELD1` ASC) VISIBLE,
  CONSTRAINT `fk_controls_driver1`
    FOREIGN KEY (`driver_FIELD1`)
    REFERENCES `f1`.`driver` (`FIELD1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `f1`.`driverstand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `f1`.`driverstand` (
  `FIELD1` INT(11) NOT NULL,
  `driverStandingsId` INT(11) NOT NULL,
  `raceId` INT(11) NOT NULL,
  `driverId` INT(11) NOT NULL,
  `points` DECIMAL(5,2) NOT NULL,
  `position` INT(11) NOT NULL,
  `positionText` VARCHAR(3) NOT NULL,
  `wins` INT(11) NOT NULL,
  `driver_FIELD1` INT(11) NOT NULL,
  PRIMARY KEY (`FIELD1`),
  INDEX `fk_driverstand_driver_idx` (`driver_FIELD1` ASC) VISIBLE,
  CONSTRAINT `fk_driverstand_driver`
    FOREIGN KEY (`driver_FIELD1`)
    REFERENCES `f1`.`driver` (`FIELD1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `f1`.`resultats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `f1`.`resultats` (
  `resultId` INT(11) NOT NULL,
  `raceId` INT(11) NOT NULL,
  `driverId` INT(11) NOT NULL,
  `constructorId` INT(11) NOT NULL,
  `numb` INT(11) NULL DEFAULT NULL,
  `grid` INT(11) NOT NULL,
  `post` INT(11) NULL DEFAULT NULL,
  `positionText` VARCHAR(2) NOT NULL,
  `positionOrder` INT(11) NOT NULL,
  `points` DECIMAL(4,2) NOT NULL,
  `laps` INT(11) NOT NULL,
  `temps` VARCHAR(10) NULL DEFAULT NULL,
  `milliseconds` INT(11) NULL DEFAULT NULL,
  `fastestLap` INT(11) NULL DEFAULT NULL,
  `level` INT(11) NULL DEFAULT NULL,
  `fastestLapTime` VARCHAR(7) NULL DEFAULT NULL,
  `fastestLapSpeed` VARCHAR(7) NULL DEFAULT NULL,
  `statusId` INT(11) NOT NULL,
  `statue_statusId` INT(11) NOT NULL,
  `circuits_circuitId` INT(100) NOT NULL,
  PRIMARY KEY (`resultId`),
  INDEX `fk_resultats_circuits1_idx` (`circuits_circuitId` ASC) VISIBLE,
  CONSTRAINT `fk_resultats_circuits1`
    FOREIGN KEY (`circuits_circuitId`)
    REFERENCES `f1`.`circuits` (`circuitId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `f1`.`qualif`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `f1`.`qualif` (
  `FIELD1` INT(11) NOT NULL,
  `qualifyId` INT(11) NOT NULL,
  `raceId` INT(11) NOT NULL,
  `driverId` INT(11) NOT NULL,
  `constructorId` INT(11) NOT NULL,
  `number` INT(11) NOT NULL,
  `position` INT(11) NOT NULL,
  `q1` VARCHAR(9) NOT NULL,
  `q2` VARCHAR(8) NOT NULL,
  `q3` VARCHAR(8) NOT NULL,
  `resultats_resultId` INT(11) NOT NULL,
  PRIMARY KEY (`FIELD1`, `resultats_resultId`),
  INDEX `fk_qualif_resultats1_idx` (`resultats_resultId` ASC) VISIBLE,
  CONSTRAINT `fk_qualif_resultats1`
    FOREIGN KEY (`resultats_resultId`)
    REFERENCES `f1`.`resultats` (`resultId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
